"""Add CARS ablation component flags to residual_connectors

Revision ID: ee3a3eb4cdd6
Revises: 
Create Date: 2026-01-27 00:30:00.779449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3a3eb4cdd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add CARS ablation component flags with default=True for existing rows
    op.add_column('residual_connectors', sa.Column('enable_k_conf', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('residual_connectors', sa.Column('enable_k_risk', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove CARS ablation component flags
    op.drop_column('residual_connectors', 'enable_k_risk')
    op.drop_column('residual_connectors', 'enable_k_conf')
    # ### end Alembic commands ###
